/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        blood: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#CC2936',
          500: '#A4161A',
          600: '#8B0000',
          700: '#660000',
          800: '#4a0000',
          900: '#300000',
        },
        dark: {
          100: '#404040',
          200: '#333333',
          300: '#2C2C2C',
          400: '#262626',
          500: '#1E1E1E',
          600: '#171717',
          700: '#0f0f0f',
        },
        success: {
          50: '#f0fdf4',
          100: '#dcfce7',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
        },
        warning: {
          50: '#fffbeb',
          100: '#fef3c7',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
        },
        info: {
          50: '#eff6ff',
          100: '#dbeafe',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
        },
        background: "#f9f9f9",
        "inverse-surface": "#2f3131",
        "on-error": "#ffffff",
        "on-primary-fixed": "#410000",
        "surface-dim": "#dadada",
        "surface-container-high": "#e8e8e8",
        "secondary-fixed": "#e2e2e7",
        "tertiary-container": "#424242",
        "on-primary-container": "#ff907f",
        "surface": "#f9f9f9",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#c6c6cb",
        "primary-fixed": "#ffdad4",
        "on-primary-fixed-variant": "#920703",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#8b0000",
        "primary-fixed-dim": "#ffb4a8",
        "surface-container-highest": "#e2e2e2",
        "surface-tint": "#b52619",
        "primary": "#610000",
        "on-tertiary-fixed": "#1b1c1c",
        "secondary": "#5d5e63",
        "tertiary": "#2c2c2c",
        "on-secondary-container": "#616267",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#5a403c",
        "tertiary-fixed-dim": "#c8c6c6",
        "on-tertiary-fixed-variant": "#474747",
        "on-secondary-fixed": "#1a1c1f",
        "on-primary": "#ffffff",
        "outline-variant": "#e3beb8",
        "outline": "#8e706b",
        "surface-container-low": "#f3f3f4",
        "inverse-primary": "#ffb4a8",
        "secondary-container": "#dfdfe4",
        "inverse-on-surface": "#f0f1f1",
        "surface-bright": "#f9f9f9",
        "tertiary-fixed": "#e4e2e2",
        "on-surface": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        "on-tertiary-container": "#b0aeae",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#45474b",
        "surface-container": "#eeeeee",
        "on-background": "#1a1c1c"
      },
      fontFamily: {
        inter: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        "headline-lg-mobile": ["Manrope"],
        "label-md": ["Inter"],
        "headline-lg": ["Manrope"],
        "headline-md": ["Manrope"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-xl": ["Manrope"]
      },
      boxShadow: {
        'soft': '0 2px 15px rgba(0, 0, 0, 0.05)',
        'card': '0 4px 6px -1px rgba(0, 0, 0, 0.07), 0 2px 4px -2px rgba(0, 0, 0, 0.05)',
        'elevated': '0 10px 25px -5px rgba(0, 0, 0, 0.08), 0 4px 6px -4px rgba(0, 0, 0, 0.04)',
        'glow': '0 0 20px rgba(139, 0, 0, 0.15)',
        'glow-lg': '0 0 40px rgba(139, 0, 0, 0.2)',
      },
      borderRadius: {
        'xl': '12px',
        '2xl': '16px',
        '3xl': '24px',
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'full': '9999px'
      },
      spacing: {
        "margin-desktop": "5rem",
        "max-width": "1280px",
        "unit": "4px",
        "margin-mobile": "1rem",
        "gutter": "1.5rem"
      },
      fontSize: {
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      },
      animation: {
        'fade-in': 'fadeIn 0.4s ease-out',
        'fade-in-up': 'fadeInUp 0.5s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-in-left': 'slideInLeft 0.3s ease-out',
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'blood-drop': 'bloodDrop 1.5s ease-in-out infinite',
        'spin-slow': 'spin 2s linear infinite',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
        'count-up': 'countUp 0.6s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        bloodDrop: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.7' },
          '50%': { transform: 'scale(1.15)', opacity: '1' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
        countUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}
